dependencies:
  scala:
    - io.delta:delta-core_2.12:1.0.0
    - org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2

spark:
  properties:
    spark.driver.memory: 4g
    spark.executor.memory: 8g
    spark.driver.userClasspathFirst: true
    spark.executor.userClasspathFirst: true
  spark_submit_args: "--packages io.delta:delta-core_2.12:1.0.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 --conf \"spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension\" --conf \"spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog\""
  dist_classpath_filter: hadoop.*\.jar

listen:
  host: 0.0.0.0

storage:
  dir: /opt/notebooks
  mounts:
    examples:
      dir: examples
